baseURL               = "https://nav.crayon.vip"
languageCode          = "zh-CN"
title                 = "小新的导航站"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "docs"					# 站点静态文件保存目录


[params]
    author        = "Jason Liu"
    description   = "小新的导航站 | WebStack-Hugo BY Jason Liu"
    upload        = "#"  # 左侧导航栏的"网站提交"
    about         = "#"	# 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/iJason-Liu/WebStack-Hugo"  
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "小新的导航站"			  # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.png"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					# 默认站点为深色(夜间)模式
    yiyan         = true                    # 默认启用一言服务

[params.seo]    
    baiduhmid     = ''		        # 百度统计 hm.src 的 ID
    baiduSiteVer  = ''				# 百度HTML标签验证(baidu-site-verification)
    tj51laid      = ''              # 51.LA 网站统计
    tj51lack      = ''

[params.qweather]    #和风天气key
    key = "a2199007974e45058c3c3e0ba101ea35"

[params.images]
    favicon           = "assets/images/favicon.ico"
    searchImageL      = "assets/images/bg-light.jpg"	 # 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dark.jpg"		 # 搜索部分深色背景图
    logoExpandLight   = "assets/images/logo-expand-light.png"
    logoExpandDark    = "assets/images/logo-expand-dark.png"
    logoCollapseLight = "assets/images/logo.png"
    logoCollapseDark  = "assets/images/logo.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了您的权益，请联系删除相关内容，联系邮箱：crayon955@qq.com <br/>&copy; 2024 - {year} By [Jason Liu](https://crayon.vip) |  [滇ICP备2023001154号-1](https://beian.miit.gov.cn/)<br/>'
